[package]
name = "embeddb-server"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
embeddb = { path = "../embeddb" }
tracing.workspace = true
tracing-subscriber.workspace = true
